# Шаг 1: Сборка React (Node.js)
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Шаг 2: Запуск Nginx для раздачи статики
FROM nginx:alpine
# Копируем собранный фронт
COPY --from=build /app/dist /usr/share/nginx/html
# Копируем наш конфиг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]